### ISSUE TITLE
Once it's compiled, how do you upload it on the arduino?

### ISSUE THREAD

**Issue by jdrouet** [avr-rust/ruduino#16]
Hi!
I finally managed to build this project using the branch `avr-use-correct-addrspace` from https://github.com/dylanmckay/rust.git
Now I have the `.elf` file, but how can I upload it to my arduino nano?

**Comment by Restioson** [comment]
[`avrdude`](https://www.nongnu.org/avrdude/)

**Comment by shepmaster** [comment]
[My specific example of using it](https://github.com/shepmaster/rust-arduino-blink-led-no-core-with-cargo/blob/c84d5b225cfce8aac5068ed841c086d45459a000/Makefile#L18)
