### ISSUE TITLE
no value available for environment variable 'AVR_CPU_FREQUENCY_HZ'

### ISSUE THREAD

**Issue by conorbros** [avr-rust/ruduino#37]
I was getting set up following the [blink example](https://book.avr-rust.com/003.3-example-building-blink.html) and I got this error. I had to set the environment variable manually myself. Perhaps this could be set to a reasonable default or be more clear in the book that you may have to set this yourself?

**Comment by dylanmckay** [comment]
Good point. I don't think it is safe to set a default, but more documentation on it would certainly be a good thing.

**Comment by conorbros** [comment]
Cheers for the quick response. I'll make a PR :)
